# Generated by Django 5.1 on 2024-08-15 00:05

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(default="default", max_length=100)),
                ("body", tinymce.models.HTMLField(verbose_name="Content")),
            ],
        ),
        migrations.CreateModel(
            name="BaseData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_img",
                    models.ImageField(
                        blank=True,
                        default="chipped2.png",
                        null=True,
                        upload_to="company_Logo",
                    ),
                ),
                ("logo_name", models.CharField(default="Chipped", max_length=100)),
                ("footer", models.CharField(default="Update Footer ", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(
                        blank=True, default="https://www.facebook.com/", null=True
                    ),
                ),
                (
                    "whatsapp_link",
                    models.URLField(
                        blank=True, default="https://web.whatsapp.com", null=True
                    ),
                ),
                (
                    "linkedIn_link",
                    models.URLField(
                        blank=True, default="https://www.linkedin.com/", null=True
                    ),
                ),
                (
                    "twitter_link",
                    models.URLField(
                        blank=True, default="https://twitter.com", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopFooterHeading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(default="default", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AboutList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="default", max_length=100)),
                ("image", models.ImageField(upload_to="about_images")),
                (
                    "desc",
                    models.TextField(
                        default="Please write the description here", max_length=600
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopFooterContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(default="default", max_length=200)),
                ("url", models.URLField(blank=True, default="https://..", null=True)),
                (
                    "heading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to="main.topfooterheading",
                    ),
                ),
            ],
        ),
    ]
