# Generated by Django 4.2.7 on 2024-04-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programming_languages",
            old_name="color",
            new_name="PL_display_color",
        ),
        migrations.RenameField(
            model_name="programming_languages",
            old_name="images",
            new_name="PL_image_logo",
        ),
        migrations.RenameField(
            model_name="programming_languages",
            old_name="p_name",
            new_name="PL_name",
        ),
        migrations.RemoveField(
            model_name="programming_languages",
            name="projects",
        ),
        migrations.AddField(
            model_name="programming_languages",
            name="no_of_projects",
            field=models.CharField(default="no_of_projects", max_length=200, null=True),
        ),
    ]
