# Generated by Django 4.2.7 on 2024-04-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_color_programming_languages_pl_display_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedata",
            name="logo_img",
            field=models.ImageField(
                blank=True, default="chipped2.png", null=True, upload_to="company_Logo"
            ),
        ),
    ]
