# Generated by Django 5.1 on 2024-10-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "curriculum",
                    models.CharField(
                        choices=[
                            ("CBC", "Competency-Based Curriculum"),
                            ("8-4-4", "8-4-4 System"),
                            ("SNE", "Special Needs Education"),
                        ],
                        max_length=5,
                    ),
                ),
                ("has_sne", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="schools.educationstage",
                    ),
                ),
            ],
            options={
                "ordering": ["stage", "order"],
                "unique_together": {("name", "stage", "curriculum")},
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=100)),
                ("school_type", models.CharField(max_length=50)),
                ("established_date", models.DateField()),
                ("about", models.TextField(default="please enter school information")),
                ("capacity", models.IntegerField(default="0")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "education_levels",
                    models.ManyToManyField(
                        blank=True, related_name="schools", to="schools.educationlevel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=200)),
                ("whatsapp", models.URLField(default="https://wa.me/enternumber")),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="schools.school",
                    ),
                ),
            ],
        ),
    ]
