# Generated by Django 5.1 on 2024-08-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "school_type",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        max_length=20,
                    ),
                ),
                ("education_levels", models.JSONField()),
            ],
        ),
    ]
