# Generated by Django 5.1 on 2024-10-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationstage",
            name="name",
            field=models.CharField(
                choices=[
                    ("EYE", "Early Years Education"),
                    ("UPE", "Upper Primary Education"),
                    ("SSE", "Secondary School Education"),
                ],
                max_length=5,
            ),
        ),
    ]
