# Generated by Django 5.1 on 2024-10-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_alter_educationstage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationstage",
            name="name",
            field=models.CharField(
                choices=[
                    ("Early Years Education", "Early Years Education"),
                    ("Upper Primary Education", "Upper Primary Education"),
                    ("Secondary School Education", "Secondary School Education"),
                ],
                max_length=50,
            ),
        ),
    ]
